version: '3'
services:
  selenium:
    image: selenium/standalone-chrome
    shm_size: '2gb'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:4444"]
      interval: 1s
      timeout: 1s
      retries: 10
      start_period: 1s
  test:
    build:
      context: .
    depends_on:
      selenium:
        condition: service_healthy
#    volumes:
#      - .:/app
    environment:
      - SELENIUM_REMOTE_URL=http://selenium:4444/wd/hub